server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  datasource:
    port: 9000
    url: jdbc:postgresql://localhost:${spring.datasource.port}/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:
    hibernate:
      ddl-auto: update